backend:
  name: github
  repo: yicheng340/isomer-cms-demo
  branch: master

publish_mode: editorial_workflow
media_folder: "images"

site_url: https://angry-minsky-7a4db6.netlify.com
logo_url: https://angry-minsky-7a4db6.netlify.com/images/isomer-logo.svg

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{title}}"

    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        default: "simple-page"
        options:
          - {label: "Simple Page", value: "simple-page"}
          - {label: "Left Nav", value: "leftnav-page-content"}
          - {label: "Board of Directors", value: "board-of-directors"}
          - {label: "Contact Us", value: "contact-us"}
        hint: "What kind of page would you like?"
      - {label: "Title", name: "title", widget: "string", hint: "Title for the page"}
      - {name: "permalink", widget: "hidden", default: "{{title}}"} # for experimentation
      - {label: "Breadcrumb", name: "breadcrumb", widget: "string", hint: "A human-readable path leading to this Page"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "press-releases"
    label: "Press Releases"
    label_singular: "Press Release"
    folder: "news/press-releases/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    
    # preview_path: "news/press-releases/{{permalink}}"
    
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", hint: "Title for the press release"}
      - {label: "Date", name: "date", widget: "datetime", hint: "Publication date for this release"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "URL this release will be at ugh how do I explain this"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "forum-letter-replies"
    label: "Forum Letter Replies"
    label_singular: "Forum Letter Reply"
    folder: "news/forum-letter-replies/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    
    # preview_path: "news/forum-letter-replies/{{permalink}}"
    
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", hint: "Title for the letter reply"}
      - {label: "Date", name: "date", widget: "datetime", "Publication date for this reply"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "URL this release will be at ugh how do I explain this"}
      - {label: "Body", name: "body", widget: "markdown"}
